apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiggle-coordinator.fullname" . }}
  labels:
    {{- include "wiggle-coordinator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "wiggle-coordinator.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
